baseURL: "https://63024d5a1f6b4b2681bbc038--stunning-llama-bc12c7.netlify.app/"
languageCode: en-us
title: My New Hugo Trial
theme: PaperMod

menu:
  main:
    - identifier: catogeries
      name: Catagories
      url: /catagories/
      weight: 10
    - identifier: Tags
      name: tags
      url: /tags/
      weight: 30
